-- File: NAND.vhd
-- Generated by MyHDL 0.10
-- Date: Tue Apr 16 16:44:23 2019


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_010.all;

entity NAND is
    port (
        a: in std_logic;
        b: in std_logic;
        z: out std_logic
    );
end entity NAND;
-- input: a, b
-- output z

architecture MyHDL of NAND is



begin




NAND_NAND_BEHAVE: process (a, b) is
    variable activation: integer;
begin
    activation := to_integer((((-10) * to_signed(a, 2)) + ((-10) * to_signed(b, 2))) + 10);
    if (activation < 0) then
        z <= '0';
    else
        z <= '1';
    end if;
end process NAND_NAND_BEHAVE;

end architecture MyHDL;
