-- File: OR.vhd
-- Generated by MyHDL 0.10
-- Date: Thu Apr 11 15:36:01 2019


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_010.all;

entity OR is
    port (
        a: in std_logic;
        b: in std_logic;
        z: out std_logic
    );
end entity OR;
-- input: a, b
-- output: z

architecture MyHDL of OR is



begin




OR_OR_BEHAVE: process (b, a) is
    variable activation: integer;
begin
    activation := to_integer(((10 * to_unsigned(a, 1)) + (10 * to_unsigned(b, 1))) - 10);
    if (activation < 0) then
        z <= '0';
    else
        z <= '1';
    end if;
end process OR_OR_BEHAVE;

end architecture MyHDL;
